// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBmY-_6o_M1SsqlUsW0HM1ob23EaKGC-7E",
    authDomain: "mypets-healthbook.firebaseapp.com",
    databaseURL: "https://mypets-healthbook-default-rtdb.firebaseio.com",
    projectId: "mypets-healthbook",
    storageBucket: "mypets-healthbook.appspot.com",
    messagingSenderId: "212788224879",
    appId: "1:212788224879:web:3ed68afc95f14126a3fe9a",
    measurementId: "G-9MDXPMQYDV",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmY-_6o_M1SsqlUsW0HM1ob23EaKGC-7E',
    appId: '1:212788224879:android:85e1b0e58b07f594a3fe9a',
    messagingSenderId: '212788224879',
    projectId: 'mypets-healthbook',
    storageBucket: 'mypets-healthbook.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDLcX_y-dkNgzaRXpk2z7R0xQ0zzR-IFRg',
  //   appId: '1:627821127710:ios:d855737ee95c939e15260f',
  //   messagingSenderId: '627821127710',
  //   projectId: 'scappflutter',
  //   storageBucket: 'scappflutter.appspot.com',
  //   androidClientId:
  //       '627821127710-848vk9dsbns65h75o34vrvpm8lkgpd23.apps.googleusercontent.com',
  //   iosClientId:
  //       '627821127710-aak73eb7g4bhbujb1ghk36v9f3ui0qur.apps.googleusercontent.com',
  //   iosBundleId: 'com.simplecomercio',
  // );
}
